services:
  frontend:
    build: .
    image: albaeus/futsal-fe
    container_name: futsal-fe
    ports:
      - "3001:80"
    restart: always
    networks:
      - futsal-network

networks:
  futsal-network:
    external: true
